name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # Change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Blogg-backend # Run only inside `Blogg-backend`

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy src/index.ts # Explicitly set entry point
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
