name: Deploy Backend Worker

on:
  push:
    branches:
      - main
    # paths:
    #   - "Blogg-backend/**"   # only run when backend files change

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    defaults:
      run:
        working-directory: Blogg-backend # set backend folder as working dir

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (use LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: Blogg-backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy src/index.ts --name=blogg-backend --compatibility-date=2025-08-18
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
